<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_infokatalon.com_fa fa-dribbble fa-fw fa-3x</name>
   <tag></tag>
   <elementGuidId>637826af-23d5-4ad1-9d35-5df8f74604b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[3]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-dribbble.fa-fw.fa-3x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5f0cf000-e91b-4f83-8d7c-b543a60a2aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-dribbble fa-fw fa-3x</value>
      <webElementGuid>aca61171-1792-4ec0-bf36-35354ef0f7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/footer[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-10 col-lg-offset-1 text-center&quot;]/ul[@class=&quot;list-inline&quot;]/li[3]/a[1]/i[@class=&quot;fa fa-dribbble fa-fw fa-3x&quot;]</value>
      <webElementGuid>205b5739-0702-4267-9070-3d4bdcb88ac9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/i</value>
      <webElementGuid>e06f8fc9-f425-4171-a05f-f2f0312fc7bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
